#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x17ACBA8DFA970E17 (richard@hughsie.com)
#
Name     : colord-gtk
Version  : 0.1.26
Release  : 1
URL      : https://www.freedesktop.org/software/colord/releases/colord-gtk-0.1.26.tar.xz
Source0  : https://www.freedesktop.org/software/colord/releases/colord-gtk-0.1.26.tar.xz
Source99 : https://www.freedesktop.org/software/colord/releases/colord-gtk-0.1.26.tar.xz.asc
Summary  : colord-gtk is GTK integration for libcolord
Group    : Development/Tools
License  : LGPL-3.0
Requires: colord-gtk-bin
Requires: colord-gtk-lib
Requires: colord-gtk-locales
Requires: colord-gtk-data
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(colord)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(lcms2)

%description
colord-gtk
colord-gtk is a GTK+ support library.
See http://colord.hughsie.com/ for more details.

%package bin
Summary: bin components for the colord-gtk package.
Group: Binaries
Requires: colord-gtk-data

%description bin
bin components for the colord-gtk package.


%package data
Summary: data components for the colord-gtk package.
Group: Data

%description data
data components for the colord-gtk package.


%package dev
Summary: dev components for the colord-gtk package.
Group: Development
Requires: colord-gtk-lib
Requires: colord-gtk-bin
Requires: colord-gtk-data
Provides: colord-gtk-devel

%description dev
dev components for the colord-gtk package.


%package lib
Summary: lib components for the colord-gtk package.
Group: Libraries
Requires: colord-gtk-data

%description lib
lib components for the colord-gtk package.


%package locales
Summary: locales components for the colord-gtk package.
Group: Default

%description locales
locales components for the colord-gtk package.


%prep
%setup -q -n colord-gtk-0.1.26

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491756496
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1491756496
rm -rf %{buildroot}
%make_install
%find_lang colord-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cd-convert

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/ColordGtk-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/colord-1/colord-gtk.h
/usr/include/colord-1/colord-gtk/cd-sample-widget.h
/usr/include/colord-1/colord-gtk/cd-sample-window.h
/usr/include/colord-1/colord-gtk/cd-version.h
/usr/include/colord-1/colord-gtk/cd-window-sync.h
/usr/include/colord-1/colord-gtk/cd-window.h
/usr/lib64/libcolord-gtk.so
/usr/lib64/pkgconfig/colord-gtk.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcolord-gtk.so.1
/usr/lib64/libcolord-gtk.so.1.0.3

%files locales -f colord-gtk.lang
%defattr(-,root,root,-)

