#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x17ACBA8DFA970E17 (richard@hughsie.com)
#
Name     : colord-gtk
Version  : 0.3.0
Release  : 9
URL      : https://www.freedesktop.org/software/colord/releases/colord-gtk-0.3.0.tar.xz
Source0  : https://www.freedesktop.org/software/colord/releases/colord-gtk-0.3.0.tar.xz
Source1  : https://www.freedesktop.org/software/colord/releases/colord-gtk-0.3.0.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: colord-gtk-bin = %{version}-%{release}
Requires: colord-gtk-data = %{version}-%{release}
Requires: colord-gtk-lib = %{version}-%{release}
Requires: colord-gtk-license = %{version}-%{release}
Requires: colord-gtk-locales = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : colord-dev
BuildRequires : docbook-xml
BuildRequires : glib-dev
BuildRequires : gtk-doc
BuildRequires : pkgconfig(colord)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk4)

%description
colord-gtk
colord-gtk is a GTK+ support library.
See http://colord.hughsie.com/ for more details.

%package bin
Summary: bin components for the colord-gtk package.
Group: Binaries
Requires: colord-gtk-data = %{version}-%{release}
Requires: colord-gtk-license = %{version}-%{release}

%description bin
bin components for the colord-gtk package.


%package data
Summary: data components for the colord-gtk package.
Group: Data

%description data
data components for the colord-gtk package.


%package dev
Summary: dev components for the colord-gtk package.
Group: Development
Requires: colord-gtk-lib = %{version}-%{release}
Requires: colord-gtk-bin = %{version}-%{release}
Requires: colord-gtk-data = %{version}-%{release}
Provides: colord-gtk-devel = %{version}-%{release}
Requires: colord-gtk = %{version}-%{release}

%description dev
dev components for the colord-gtk package.


%package doc
Summary: doc components for the colord-gtk package.
Group: Documentation

%description doc
doc components for the colord-gtk package.


%package lib
Summary: lib components for the colord-gtk package.
Group: Libraries
Requires: colord-gtk-data = %{version}-%{release}
Requires: colord-gtk-license = %{version}-%{release}

%description lib
lib components for the colord-gtk package.


%package license
Summary: license components for the colord-gtk package.
Group: Default

%description license
license components for the colord-gtk package.


%package locales
Summary: locales components for the colord-gtk package.
Group: Default

%description locales
locales components for the colord-gtk package.


%prep
%setup -q -n colord-gtk-0.3.0
cd %{_builddir}/colord-gtk-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1645038195
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dman=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/colord-gtk
cp %{_builddir}/colord-gtk-0.3.0/COPYING %{buildroot}/usr/share/package-licenses/colord-gtk/f45ee1c765646813b442ca58de72e20a64a7ddba
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang colord-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cd-convert

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/ColordGtk-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/colord-1/colord-gtk.h
/usr/include/colord-1/colord-gtk/cd-sample-widget.h
/usr/include/colord-1/colord-gtk/cd-sample-window.h
/usr/include/colord-1/colord-gtk/cd-version.h
/usr/include/colord-1/colord-gtk/cd-window-sync.h
/usr/include/colord-1/colord-gtk/cd-window.h
/usr/lib64/libcolord-gtk.so
/usr/lib64/libcolord-gtk4.so
/usr/lib64/pkgconfig/colord-gtk.pc
/usr/lib64/pkgconfig/colord-gtk4.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/colord-gtk/colord-gtk-CdSampleWindow.html
/usr/share/gtk-doc/html/colord-gtk/colord-gtk-cd-version.html
/usr/share/gtk-doc/html/colord-gtk/colord-gtk-cd-window.html
/usr/share/gtk-doc/html/colord-gtk/colord-gtk.devhelp2
/usr/share/gtk-doc/html/colord-gtk/home.png
/usr/share/gtk-doc/html/colord-gtk/index.html
/usr/share/gtk-doc/html/colord-gtk/ix01.html
/usr/share/gtk-doc/html/colord-gtk/left-insensitive.png
/usr/share/gtk-doc/html/colord-gtk/left.png
/usr/share/gtk-doc/html/colord-gtk/libcolord-glib-helpers.html
/usr/share/gtk-doc/html/colord-gtk/libcolord-gtk.html
/usr/share/gtk-doc/html/colord-gtk/license.html
/usr/share/gtk-doc/html/colord-gtk/right-insensitive.png
/usr/share/gtk-doc/html/colord-gtk/right.png
/usr/share/gtk-doc/html/colord-gtk/style.css
/usr/share/gtk-doc/html/colord-gtk/up-insensitive.png
/usr/share/gtk-doc/html/colord-gtk/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcolord-gtk.so.1
/usr/lib64/libcolord-gtk.so.1.0.3
/usr/lib64/libcolord-gtk4.so.1
/usr/lib64/libcolord-gtk4.so.1.0.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/colord-gtk/f45ee1c765646813b442ca58de72e20a64a7ddba

%files locales -f colord-gtk.lang
%defattr(-,root,root,-)

